implemented function of register
okapiinosuke/Backend_twitter_clone pull request #1
Opened 2021-11-06 04:30 UTC by okapiinosuke

新規ユーザが本サービスを利用するためのユーザ登録機能を実装しました．

- メールアドレスとユーザ名，パスワードをフォームへ入力することでユーザの登録を行います．
- フォームに対する多様な入力に対応できることを確認するため，12個のテストを実施しました．

以下，実際に作成したページのスクリーンショット

- スタートページ
![image](https://user-images.githubusercontent.com/47509184/140466348-de5e921a-3b50-453f-8379-5773da36b07a.png)

- 登録画面
![image](https://user-images.githubusercontent.com/47509184/140466638-6688c6f9-ef74-4883-8792-02e188d06e60.png)

- 登録画面（入力に対して何らかのミスがあった場合）
![screeenshot_2021-11-05_152959](https://user-images.githubusercontent.com/47509184/140468344-5c2f5071-b605-4848-b8eb-8b9a9f4528eb.png)

- 登録完了画面
![screenshot_2021-11-05_153114](https://user-images.githubusercontent.com/47509184/140468368-a56e381f-a936-4133-bf64-e5446d97689a.png)

2021-11-06 05:52 UTC, yusukekaneko commented
指摘した修正点に関しては問題なさそうです。

ただ、アプリのフォルダ名であるTwitterFuncから推察するに、アプリをTwitterFuncのフォルダで一元管理するのは避けた方が良いです。これは、今後機能を追加していくにあたり、コードが複雑化して可読性が下がってしまう恐れがあるからです。その為、まずはTwitterFuncではなく、users やaccount（名前は適当でいいです）といったアプリ名に変更し、そこでユーザー関連の機能を管理するようにしてみて下さい。

また、今回プログラムを実行するに当たって仮想環境はどうされていますか？

2021-11-06 09:57 UTC, okapiinosuke commented
anacondaにてdjangoの仮想環境を作成しています．
pythonとdjango関連のバージョンはそれぞれ以下の通りになっています．
python=3.8.11
django=3.2.7
django-bootstrap4=21.1

2021-11-07 02:06 UTC, YusukeKaneko commented on account/apps.py
> +    name = 'TwitterFunc'
app名の変更に伴い、ここの部分を適切な名前に変更して下さい。

2021-11-07 02:06 UTC, YusukeKaneko commented on twitter_clone/settings.py
> +    'TwitterFunc.apps.TwitterfuncConfig',
ここも同様に名前を変更して下さい。（その後、migrationとmigrateも忘れずに行ってください。）

2021-11-07 02:06 UTC, YusukeKaneko commented on twitter_clone/urls.py
> +    path('', include('TwitterFunc.urls')),
名前を変更して下さい。
また、views.pyやhtmlコードについてもアプリ名の変更があると思うので同様に行ってください。

2021-11-07 02:06 UTC, YusukeKaneko commented on account/urls.py
> +
urls.pyにはapp_nameを記載するようにして下さい。

2021-11-07 05:55 UTC, okapiinosuke commented
上記のコメントについて修正を行いました．

2021-11-07 06:57 UTC, yusukekaneko commented on account/forms.py
> +from .models import Account
import順を整理した方が見やすくなると思います（他の場所も同様）。
VSCodeを使用しているようであれば、Pythonの拡張を入れることでimport順を整理することが出来ます。

2021-11-07 11:23 UTC, okapiinosuke commented on account/forms.py
> +from .models import Account
isortをpipして適用したものをプッシュしました．
確認の程，お願いします．

2021-11-08 01:53 UTC, yusukekaneko approved these changes
LGTM

2021-11-09 10:23 UTC, fumiharun11 commented
> anacondaにてdjangoの仮想環境を作成しています． pythonとdjango関連のバージョンはそれぞれ以下の通りになっています． python=3.8.11 django=3.2.7 django-bootstrap4=21.1

使用ライブラリのバージョン管理を`requirements.txt`を作成して明記するようにしてください。

2021-11-09 11:42 UTC, fumiharun11 commented on twitter_clone/settings.py
> +STATIC_ROOT = os.path.join(BASE_DIR, 'static')
`BASE_DIR`がos.pathではなくpathlibを用いているため、pathlibのフォーマットで統一しましょう。

2021-11-09 11:42 UTC, fumiharun11 commented on account/models.py
> +class Account(User):
既存の`User`クラスを継承して定義している意図は何ですか？
CustomUserクラスとして扱うことを目的としていますか？DB上は`User`と1:1の関係であるテーブルとして存在しているので、意味のある設計になっているか確認です。

2021-11-09 11:42 UTC, fumiharun11 commented on account/models.py
> +from django.conf import settings
unused importはPRに含めないようにしましょう。

2021-11-09 11:42 UTC, fumiharun11 commented on account/views.py
> +            return redirect('/register/complete')
Basic Web Backendの課題『Djangoアプリ開発』で既に登場している名前空間を利用して逆引きのフォーマットで記述してみましょう。
該当課題サイト: https://docs.djangoproject.com/ja/3.0/intro/tutorial03/#namespacing-url-names

より詳細にURLの名前空間について確認する際は以下の公式ドキュメントを読んでみましょう！
Google検索では『Django url namespace』と検索すると上位に出てきます。
参考docs: https://docs.djangoproject.com/ja/3.2/topics/http/urls/#url-namespaces

2021-11-09 11:42 UTC, fumiharun11 commented on account/views.py
> +def start(request):
今回は課題なので修正必須ではないですが、命名規則上suffixとして`xxx_view`という関数名になっているとview関数であることを認識しやすいので個人的にお勧めです。

2021-11-09 11:42 UTC, fumiharun11 commented on account/forms.py
> +        error_messages={'required': 'Please enter your email'},
フォームが返すメッセージは英語のままだけど問題ないですか？(一応確認)

2021-11-09 11:42 UTC, fumiharun11 commented on account/views.py
> +from django.views.generic.edit import CreateView
unused importに注意です

2021-11-09 11:42 UTC, fumiharun11 commented on account/tests.py
> +        self.client = Client()
継承元の`TestCase`クラス(厳密には更に親のクラス)でインスタンス変数が定義されているのでここでは不要です。

2021-11-09 11:42 UTC, fumiharun11 commented on account/tests.py
> +            path='/register/',
一つのViewに対して複数のメソッドで度々pathを定義するとメンテナンスが面倒な印象があるので、`setUp`メソッド等で`self.url = 'app_name:view_name'`を定義して使い回す方針にするのも有りだと思います。

2021-11-09 11:42 UTC, fumiharun11 commented on account/tests.py
> +        self.assertEqual(saved_accounts.count(), 1)
厳密に見ると、POST前にQuerySetのカウントが0であることを確認出来ていると更に良いと思います。
また、`username`や`email`カラムでfilterをした結果レコードが存在するかどうかをチェックする方針にすると更に丁寧になると思います。

2021-11-09 11:42 UTC, fumiharun11 commented on account/tests.py
> +        error_list = re.findall('<p style="color: red">(.+)</p>', html_str)
HTML側のスタイル変更によってテストが壊れてしまう可能性があるため、フォームにエラーが含まれているかどうかでチェックすると良いと思いますが、いかがですか？
参考: https://docs.djangoproject.com/en/3.2/ref/forms/api/#django.forms.Form.errors

2021-11-09 13:40 UTC, okapiinosuke commented on account/models.py
> +class Account(User):
色々調べながら書いたコードのため特に意味はないです．
参照したサイト：https://nmomos.com/tips/2019/07/05/django-create-usersignup/
普通であればどのクラスを継承しますか．

2021-11-15 05:52 UTC, fumiharun11 commented on account/models.py
> +class Account(User):
どこまで既存のUserモデルを拡張したいかに寄りますが、基本的に`AbstractUser`か`AbstractBaseUser`のどちらかを継承することになります。
使い方は公式docsを確認してみてください。また、イメージを掴みやすい参考記事があったので目を通してみてください。
参考記事: https://note.com/mihami383/n/n9fed6a139ea7

2022-01-19 08:40 UTC, okapiinosuke commented
上記のコメントに対して修正を行いました．

2022-01-20 16:43 UTC, Akinori13 requested changes
数点コメントしました
- myvenvはGitの管理対象から外してください。
- requirement.txtでも構わないのですが、一般的なrequirements.txtに名称を変更してください。

2022-01-20 16:43 UTC, Akinori13 commented on account/urls.py
> +register_patterns = ([
二つに分けている理由はありますか

2022-01-20 16:43 UTC, Akinori13 commented on account/views.py
> +            state = "complete"
使わないなら消しちゃってください

2022-01-20 16:43 UTC, Akinori13 commented on account/tests.py
> +    def test_is_lack_of_username(self):
formではなくpostして確認してもらいたいです！

2022-01-21 07:23 UTC, okapiinosuke commented on account/views.py
> +            state = "complete"
使っているのでそのまま残します．
ここでは，フォームの妥当性を判断し，妥当であればcompleteページへ，そうでなければエラーメッセージを出して元のページへ遷移します．

2022-01-21 07:26 UTC, okapiinosuke commented on account/urls.py
> +register_patterns = ([
この部分をコメントアウトすると以下のエラーメッセージが出力されてしまうため必要だと考えています．
![image](https://user-images.githubusercontent.com/47509184/150484405-e22e4b29-c655-4fde-ba18-20eae637cda4.png)

2022-01-21 08:28 UTC, okapiinosuke commented on account/tests.py
> +    def test_is_lack_of_username(self):
24-32行目でポストしてから，データベースにおいて確認を行っています．

2022-01-21 08:40 UTC, Akinori13 commented on account/tests.py
> +    def test_is_lack_of_username(self):
異常系エラーのチェックでもポストしてデータベースの確認してもらいたいです

2022-01-21 08:56 UTC, Akinori13 commented on account/urls.py
> +register_patterns = ([
okです。下記でも動作すると思いますが、お任せします。
```suggestion
urlpatterns = [
    path('', views.start_view, name='start'),
    path('register/', views.register_view, name='register'),
    path('register/complete/', views.complete_view, name='complete')
    path('login/', views.login_view, name='login'),
]
```

2022-01-21 09:04 UTC, okapiinosuke commented on account/urls.py
> +register_patterns = ([
上記のコードで動作を確認しました．
修正しておきます．

2022-01-22 12:40 UTC, Akinori13 requested changes
コメントしました。確認をお願いします

2022-01-22 12:40 UTC, Akinori13 commented on .gitignore
> +myvenv
最後に空行を入れましょう

2022-01-22 12:40 UTC, Akinori13 commented on account/models.py
> +    password2 = models.CharField(max_length=20, verbose_name='パスワードの再入力')
この実装は非常に危険なリスクを生じさせることがありえます。現在の実装の場合、万が一DBの情報が流出した時に、パスワードが平文で表示されます。パスワードが平文の場合、そのユーザーが他のサービスのパスワードと同一のパスワードを用いていると、そのサービスにハッカーが不正アクセスすることが可能になります。
AbstractUserはpasswordとというカラムを用意しており、formが有効であれば、password1をハッシュしてpasswordカラムに格納します。したがって、ここのpassword1とpassword2は削除してください。

2022-01-22 12:40 UTC, Akinori13 commented on account/models.py
> +    email = models.CharField(max_length=200, verbose_name='メールアドレス')
EmailFieldにしましょう

2022-01-22 12:40 UTC, Akinori13 commented on account/models.py
> +    username = models.CharField(max_length=30, unique=True, verbose_name='ユーザー名')
この実装の場合、djangoのデフォルトのusernameに対するバリデーションチェックが解除されているを認識だけしておきましょう。UnicodeUsernameValidatorを用いるかどうかはお任せます。

2022-01-22 12:40 UTC, Akinori13 commented on account/models.py
> +    password2 = models.CharField(max_length=20, verbose_name='パスワードの再入力')
デフォルトの実装は、contrib/auth/models.pyなどを確認しておきましょう

2022-01-22 12:40 UTC, Akinori13 commented on account/forms.py
> +        return password2
継承元と同一です。何も上書きしないならば消しちゃいましょう

2022-01-22 12:40 UTC, Akinori13 commented on account/models.py
> +    password2 = models.CharField(max_length=20, verbose_name='パスワードの再入力')
単にmax_lengthを設定するならば、`password = models.CharField(_('password'), max_length=20)`です。

2022-01-22 12:40 UTC, Akinori13 commented on account/models.py
> +class Account(AbstractUser):
verbose_nameは日本語に直す必要はないです。djangoはgettext_lazyにより自動的に日本語に翻訳する機能がついています。例えばAbstractBaseUserのpasswordカラムは以下の通りです
```
password = models.CharField(_('password'), max_length=128)
```
この_はgettext_lazyという関数の省略ですが、gettext_lazyが日本語にpasswordを翻訳してくれます。メールアドレスなども同様です。ですからverbose_nameを日本語で指定する必要はないわけです。

2022-01-22 12:40 UTC, Akinori13 commented on account/forms.py
> +        widget=forms.PasswordInput)
必要な箇所のみ上書きしましょう.
[参考](https://stackoverflow.com/questions/61306006/how-to-override-help-text-and-label-for-password-form-in-django)

2022-01-26 05:07 UTC, Akinori13 approved these changes

2022-01-26 05:09 UTC, merged