ログイン、ログアウト機能の実装
okapiinosuke/Backend_twitter_clone pull request #3
Opened 2022-06-03 06:32 UTC by okapiinosuke

ログイン、ログアウト機能を追加で実装しました。

- ユーザー名とパスワードを入力し、一致した場合のみホーム画面へ遷移します。

以下に、実際に作成したページのスクリーンショットを示します。
- ログイン画面
![image](https://user-images.githubusercontent.com/47509184/171799726-464e3c00-f217-42ce-b9cd-ce3b2bb35a7d.png)

- ホーム画面
![image](https://user-images.githubusercontent.com/47509184/171799806-71df3ccd-3965-422f-8a07-a74a2162a6b5.png)
ログアウトのリンクをクリックすると、ログイン画面に戻ります。

2022-06-04 02:36 UTC, okapiinosuke commented
![image](https://user-images.githubusercontent.com/47509184/171975195-9524bea0-e78e-470f-979d-43a0e9216978.png)
自身が考えたテストは全て通りました。

2022-06-04 12:46 UTC, YusukeKaneko commented
実装された部分については基本的に良いと思います。
ただ、先日コースが新設され、その際に最終課題の機能要件も変更されたようです。具体的には、ログイン・ログアウト機能の他に、`プロフィール機能`も機能要件に加えられたそうなので、そちらの方も実装して頂きたいです。

2022-06-04 12:53 UTC, okapiinosuke commented
@YusukeKaneko 
今年度分のバックエンドコースの最終課題の概要が載っているページを教えていただけないでしょうか。

2022-06-04 12:55 UTC, YusukeKaneko commented on account/tests.py
> +        account.save()
こちらの方がシンプルで良いと思います。
```suggestion
       Account.objects.create_user(
            email='sample@example.com', 
            username='sample',
            password='instance1'
        )
```

2022-06-04 12:55 UTC, YusukeKaneko commented on account/tests.py
> +        self.client = Client()
django.test.TestCaseクラス自体がクライアントを持っているため、このコードは不要です。

2022-06-04 12:55 UTC, YusukeKaneko commented on account/tests.py
> +        self.assertEqual(saved_accounts.count(), 1)
わざわざ代入せずとも、以下のようにして実行することも可能です（以下同様）。
```suggestion
        self.assertEqual(Account.objects.all().count(), 1)
```

2022-06-04 12:55 UTC, YusukeKaneko commented on account/tests.py
> +        account.save()
同様に、こちらの方がシンプルで良いと思います。
```suggestion
       Account.objects.create_user(
            email='sample@example.com', 
            username='sample',
            password='instance1'
        )
```

2022-06-04 12:55 UTC, YusukeKaneko commented on account/tests.py
> +        self.client=Client()
同様に、django.test.TestCaseクラス自体がクライアントを持っているため、このコードは不要です。

2022-06-04 13:00 UTC, YusukeKaneko commented
@okapiinosuke 
新しいコースは [こちら](https://classroom.google.com/c/NDQ5OTUwMTI2ODAx?cjc=iqf2nvp)になります。

2022-06-09 08:26 UTC, okapiinosuke commented
追加でプロフィールの表示・編集機能を実装しました。

- ホーム画面（更新版、編集前）
![home_view](https://user-images.githubusercontent.com/47509184/172799793-1d1ffffd-a3e1-4f55-87b6-1d0bf82f3f78.png)
左側に名前とプロフィール，右側にログアウトとプロフィールの編集リンクを配置しました。
現在、真ん中部分が空いていますが、ツイートの一覧を配置する予定です。
- プロフィール編集画面（編集前）
![profile_before](https://user-images.githubusercontent.com/47509184/172800658-5805ae7f-a75a-4456-bf25-aff6a1491108.png)
プロフィール編集画面では，現在のプロフィールを閲覧することができます。
- プロフィール編集画面（編集後）
![profile_after](https://user-images.githubusercontent.com/47509184/172800678-cb92a631-0c68-4ac5-9343-59eb1754ee7c.png)
完了ボタンを押すと、現在のプロフィールが更新されます。
- ホーム画面（編集後）
![profile_before](https://user-images.githubusercontent.com/47509184/172800724-2b7017cf-f858-41ab-b06a-5409e0dd08d0.png)
ホーム画面に戻ると、プロフィールが更新されています。

また，プロフィール編集に関するテストを追加で実施したところ、問題なく終了しました。
![test_complete](https://user-images.githubusercontent.com/47509184/172800964-65237c37-9537-4a9d-b2a7-12e99b1ea2d3.png)

2022-06-10 14:31 UTC, YusukeKaneko commented on account/forms.py
> +        fields = {'profile'}
ModelFormを継承しているのであれば、Metaクラスを活用してあげた以下のような書き方が自然かなと思います。
forms.Textareaに引数としていくつか指定してあげることで、formの大きさなどのカスタマイズも可能ですので、余力があればやってみても良いと思います。
```suggestion
class ProfileForm(forms.ModelForm):
    """
    プロフィールフォーム
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Account
        fields = {'profile'}
        widgets = {
            'profile': forms.Textarea
        }
        labels = {
            'profile': 'プロフィール'
        }
```

2022-06-10 14:31 UTC, YusukeKaneko commented on account/views.py
> +from .models import Account
unused importです。

2022-06-10 14:31 UTC, YusukeKaneko commented on account/views.py
> +    return render(request, 'account/profile.html', {'form': form})
関数名について、小文字で統一しているのであればここも小文字の方が良いと思います。
また、これはlogin_view関数にも言えることですが、GETメソッドとPOSTメソッド以外を受け付けていない場合は、最後のreturnでエラーレスポンスを返してあげた方が親切且つコード的にも分かりやすいと思います。

2022-06-13 12:02 UTC, YusukeKaneko commented
現状Djangoのテストが通っていないので、次回からは修正後にテストの確認も都度行うように心掛けるとより良いと思います。

2022-06-13 12:02 UTC, YusukeKaneko commented on account/forms.py
> +        }
EOFを追加してください。

2022-06-13 12:02 UTC, YusukeKaneko commented on account/urls.py
> +    path('profile/', views.Profile_view, name='profile'),
関数名の変更に伴いこの部分も変更する必要があります。

2022-06-13 12:02 UTC, YusukeKaneko commented on account/views.py
> +        return render(request, 'account/profile.html', {'form': form, 'request_method_error': request_method_error})
login_viewと同じ指摘です。

2022-06-14 22:49 UTC, okapiinosuke commented
上記のいただいたコメントについて修正しました。
また、追加で許可していないメソッドに対する挙動のテストを2件実施しました。
![スクリーンショット 2022-06-13 213714](https://user-images.githubusercontent.com/47509184/173701862-92964ba2-069c-4e89-b614-ebd472518f63.png)

2022-06-15 05:05 UTC, YusukeKaneko commented
以前の指摘点を修正したものを改めてコメントしておきます。
ただ、これは今回のコミットで既に修正されている為、確認次第resolvedとしてもらって大丈夫です（こちらの不手際で複雑にしてしまい申し訳ありません）。

2022-06-15 05:05 UTC, YusukeKaneko commented on account/views.py
> -    return render(request, 'account/login.html', {'form': form})
この状態では、関数としてHTTPレスポンスを返すことが出来ていない為、エラーの要因となります。
その為、適切なレスポンスを指定するようにしましょう。

2022-06-15 05:05 UTC, YusukeKaneko commented on account/views.py
> +        return render(request, 'account/login.html', {'form': form, 'request_method_error': request_method_error})
エラーレスポンスとしてこのような書き方はあまり見ないので、以下を参考にしてみて下さい。
https://docs.djangoproject.com/en/4.0/topics/http/views/
（Testing custom error viewsの項目などが参考になると思います）
https://noauto-nolife.com/post/django-http-response/

2022-06-16 09:30 UTC, Akinori13 requested changes
よくできています。数点コメントしました！

2022-06-16 09:30 UTC, Akinori13 commented on account/views.py
> +def profile_view(request):
命名的には、プロフィール画面の表示になっちゃうので、editとかupdateとか含めるといいですね！

2022-06-16 09:30 UTC, Akinori13 commented on account/models.py
> +    profile = models.TextField(
ProfileはUserとOneToOneの関係を持つモデルで定義してください

2022-06-19 15:51 UTC, Akinori13 requested changes
良い感じです。Profileモデルは、SignUpと同時に作成して、edit_profile_viewではupdateだけするようにしましょう。
そのためProfileのprofileは、defaultを""にしてあげるとよいと思います。

2022-06-25 06:39 UTC, Akinori13 approved these changes

2022-06-25 06:40 UTC, merged