ツイートの作成、詳細閲覧、削除機能の実装
okapiinosuke/Backend_twitter_clone pull request #4
Opened 2022-07-07 07:18 UTC by okapiinosuke

ツイートの作成、詳細閲覧、削除機能の実装しました。

- ホーム画面からツイートを作成できます。
- 各ツイートの右下にあるボタンを押すと、ツイートの詳細を閲覧できます。
- ツイートの詳細画面からツイートを削除できます。（ツイートの作成者限定）

以下に実際に作成したページのスクリーンショットを示します。
- ホーム画面（ツイート前）
![image](https://user-images.githubusercontent.com/47509184/177714085-4b553fbd-b018-458f-b206-5e4a284b890a.png)
左のフォームからツイートをすることができます。

- ホーム画面（ツイート後）
![image](https://user-images.githubusercontent.com/47509184/177714137-ba27fd82-4ccd-46b5-95cf-b1543dad0cf9.png)
先ほど入力したツイートが一番上に表示されました。

- ツイートの詳細画面（ツイートをした本人）
![image](https://user-images.githubusercontent.com/47509184/177714182-d48dd6c6-d096-4860-8117-54888e4f002a.png)
自身がしたツイートは右下の削除ボタンで削除することができます。

- ツイートの詳細画面（ツイートした以外の人）
![image](https://user-images.githubusercontent.com/47509184/177714209-919f9e8e-69d9-4180-969d-c32a654d1543.png)
他人のツイートは削除することができません。

今回作成したテストを含め、全て通りました。
![image](https://user-images.githubusercontent.com/47509184/177714408-3d59c577-a489-46ab-bbaf-0b3f2c6bc9c8.png)

2022-07-09 09:55 UTC, YusukeKaneko commented
基本的に良いと思います。
ただ、今回こちらの環境でユーザを新規作成した際にエラーが生じた為、そちらの環境でも同様の状況が確認された場合、修正するようにお願いします。

2022-07-09 09:55 UTC, YusukeKaneko commented on account/models.py
> +        return self.content
accountアプリの方では、その名の通りaccountに直接関係のあるモデルを定義するのに留めることを推奨します。
これはモデルに限らずですが、一つのアプリに様々な機能を追加すると、要件が分かりずらくなってしまうことやコードが肥大化し可読性が下がる要因となります。

2022-07-09 09:55 UTC, YusukeKaneko commented on account/views.py
> +        )
POSTメソッドの場合（今回はツイートをする場合）にも、GETメソッドと同じ処理を記述するのは冗長である為、returnとしてredirect処理を記述すると良いのではないかと思います。

2022-07-09 09:55 UTC, YusukeKaneko commented on account/views.py
> +            raise Http404
この処理の意味を教えて下さい。

2022-07-09 09:55 UTC, YusukeKaneko commented on account/views.py
> +            )
この部分もredirect処理を用いることで簡潔にできると思います。

2022-07-09 09:55 UTC, YusukeKaneko commented on account/models.py
> +    profile = models.TextField(_("profile"), default="")
プロフィール編集機能があることから、Profileモデルに作成日時と更新日時のフィールドも定義してあげた方が良いかと思います。

2022-07-09 10:24 UTC, okapiinosuke commented on account/views.py
> +            raise Http404
timezone.nowをdefaultにしていなかった際に、書いていた処理のため消しておきます。

2022-07-09 10:26 UTC, okapiinosuke commented on account/models.py
> +        return self.content
この場合、tweetに関係するフォームやビューも同時に別のアプリへ移動するほうが良いでしょうか？

2022-07-09 11:16 UTC, YusukeKaneko commented on account/models.py
> +        return self.content
そうして下さい。

2022-07-10 12:30 UTC, YusukeKaneko commented on account/models.py
> +    updated_at = models.DateTimeField("更新日時", auto_now=True, blank=True)
こちらでblankをTrueにしている意図はありますか？

2022-07-10 12:30 UTC, YusukeKaneko commented on tweet/urls.py
> +    path("tweet_{<int:tweet_id>}/delete", views.delete_tweet_view, name="delete_tweet"),
細かいですが、URLの命名規則として基本的にアンダースコアよりもハイフンが推奨されている為、そちらの方で命名してあげるようにして下さい。

2022-07-10 12:42 UTC, okapiinosuke commented on account/models.py
> +    updated_at = models.DateTimeField("更新日時", auto_now=True, blank=True)
特に問題がなかったため、削除しました。
入れていた意図としては、更新前のモデルでログインした際にエラーが起きていた際に、該当するコードを入れたことでエラーが解消したためです。

2022-07-11 09:26 UTC, Akinori13 requested changes
2点コメントしました

2022-07-11 09:26 UTC, Akinori13 commented on tweet/urls.py
> +    path("tweet-{<int:tweet_id>}/delete", views.delete_tweet_view, name="delete_tweet"),
以下の形式が一般的でしょう
```suggestion
    path("tweets/<int:tweet_id>", views.tweet_detail_view, name="tweet_detail"),
    path("tweets/<int:tweet_id>/delete", views.delete_tweet_view, name="delete_tweet"),
```

2022-07-11 09:26 UTC, Akinori13 commented on tweet/tests.py
> +class TweetTest(TestCase):
TweetCreateTest, TweetDetailTest, TweetDeleteTestに分けてください

2022-07-11 16:21 UTC, Akinori13 requested changes
テストOKです。少しだけ追加でコメントしています。確認をお願いします。

2022-07-11 16:21 UTC, Akinori13 commented on tweet/urls.py
> +        "tweets/{<int:tweet_id>}/delete", views.delete_tweet_view, name="delete_tweet"
僕の勉強不足でしたら大変申し訳ないですが、`{}`に何かの意味はありますか。特につける必要は感じませんがいかがでしょうか？
```
        "tweets/<int:tweet_id>/delete", views.delete_tweet_view, name="delete_tweet"
```

2022-07-11 16:21 UTC, Akinori13 commented on tweet/views.py
> +    return HttpResponseNotAllowed(["GET"])
余談ですが、`@require_http_methods(['GET'])`とかも使えますね！

2022-07-11 16:21 UTC, Akinori13 commented on account/templates/account/home.html
> +            <p>{{ field }}</p>
余談ですが、`{{field.label_tag}}`でラベルの表示も可能です

2022-07-11 16:21 UTC, Akinori13 commented on tweet/forms.py
> +        super().__init__(*args, **kwargs)
必要ないと思いますがいかがでしょうか

2022-07-12 14:00 UTC, Akinori13 commented
LGTM

2022-07-12 14:00 UTC, merged