フォロー・フォロー解除機能の実装
okapiinosuke/Backend_twitter_clone pull request #5
Opened 2022-07-13 07:52 UTC by okapiinosuke

フォロー・フォロー解除機能の実装を実装しました。

- 自分以外のユーザーに対してフォローまたは、フォロー解除できるようになりました。
- フォローまたは、フォロー解除を画面から行えるようにするために、アカウント詳細ページを作成しました。

以下に実際に作成したページのスクリーンショットを示します。

- ログインしているアカウントのアカウント詳細ページ
![image](https://user-images.githubusercontent.com/47509184/178679305-322b34bf-ef4c-4aa6-881c-bb21d84276f0.png)
ユーザー名、プロフィール、ツイートを表示します。フォロー及び、フォロー解除ボタンは表示されません。

- ログインしているアカウント以外のアカウント詳細ページ（未フォロー）
![image](https://user-images.githubusercontent.com/47509184/178679534-8765c2f1-0c8c-41f1-b981-649678453751.png)
自分以外のアカウント詳細ページには、先ほどの情報だけでなく、フォローボタンが表示されます。

- ログインしているアカウント以外のアカウント詳細ページ（既フォロー）
![image](https://user-images.githubusercontent.com/47509184/178679892-61de297d-cb2b-4369-8d7d-ba8b5699f61f.png)
フォローしている場合は、フォロー解除ボタンが表示されます。

また、今回作成したテストを含め、全て通したことを以下に示します。
![image](https://user-images.githubusercontent.com/47509184/178680152-83d1e30b-add8-439e-9ba7-f329561931fe.png)

2022-07-16 08:32 UTC, TAK848 requested changes
テストや説明も丁寧で，とてもわかりやすくて良いと思います！
いくつかコメントしたので，ご確認をお願いします。

追加で，
FollowingList（フォロー中一覧）とFollowerList（フォロワー一覧）の作成をお願いします！

2022-07-16 08:32 UTC, tak848 commented on account/models.py
> +    date_created = models.DateTimeField(auto_now_add=True)
この命名だと，どっち方向へのフォローか分かりずらいので，影響範囲は大きいですが，`followee`，`follower`としてみてはいかがでしょう？

2022-07-16 08:32 UTC, tak848 commented on account/models.py
> +        return "{} : {}".format(self.follower.username, self.following.username)
Python3.6以降で使えるfリテラルを使って，文字列は
```python
return f"{self.follower.username} : {self.following.username}"
```
のように変数を混ぜることが多い気がするのですが，いかがでしょうか？

2022-07-16 08:32 UTC, tak848 commented on account/urls.py
> +        name="follow_account",
app名で`account`とわかるので，`follow`だけでもよさそうですがいかがでしょう？

2022-07-16 08:32 UTC, tak848 commented on account/urls.py
> +    path("accounts/<int:account_id>", views.account_detail_view, name="account_detail"),
トレイリングスラッシュ（最後のスラッシュ）が抜けているので，他と統一してつけてあげましょう。

2022-07-16 08:32 UTC, TAK848 commented on account/views.py
> +        user_profile = Profile.objects.get(user=account)
accountとprofileはone to oneなので，
```suggestion
        account = get_object_or_404(Account.objects.select_related("profile"), pk=account_id)
```
だけにして，`profile`は`account.profile.`といった形で使用すると良いと思います。

[この設定](https://qiita.com/fumihiko-hidaka/items/0f619749580da5ad9ce5)などをしてチェックしてもらうと，実際SELECTの回数が減るのが確認できると思います（LOGGINGの設定はPRには含めなくて大丈夫です）

2022-07-16 08:32 UTC, TAK848 commented on account/views.py
> +        )
accountを取得して，tweetを取得して…としていますが，`[0]`とした時点でSQLが発行され，2つのクエリとなってしまっています。
おそらくやりたいことは，答えっぽくなってしまうかもしれませんが，
```python
tweet_list = Tweet.objects.select_related("user").filter(user=account).order_by("-created_at")
```
で解決するのではないでしょうか？
（Tweetを参照先のuserも一緒に取得し，絞って，ソートする。template内のtweet.userはあらかじめ取得したのでN+1にもならない）

2022-07-16 08:32 UTC, TAK848 commented on account/views.py
> +    follower = get_object_or_404(Account, pk=request.user.id)
`follower = request.user`でよさそうです

2022-07-16 08:32 UTC, TAK848 commented on account/views.py
> +@require_http_methods(["GET"])
厳密なAPIでもないのでGETでも良いことは良いのですが，データを作成するときはPOSTにしましょう（テスト要件にあわせてみる意味でも）

2022-07-16 08:32 UTC, TAK848 commented on account/views.py
> +    return redirect(f"/accounts/{account_id}")
`reverse`を使いましょう

2022-07-16 08:32 UTC, TAK848 commented on account/views.py
> +    _, is_create = FollowConnection.objects.get_or_create(
`created`や，`is_created`とした方が，状態がわかりやすい気がしますがいかがでしょう？

2022-07-18 09:09 UTC, okapiinosuke commented
アカウント詳細画面でのフォロー中のアカウントとフォローされているアカウントの一覧を表示できるようにしました。
![image](https://user-images.githubusercontent.com/47509184/179479214-d1321f83-1f28-4c53-8357-33aba51a6a67.png)
![image](https://user-images.githubusercontent.com/47509184/179479255-00d5af26-7d71-4dec-91b5-7ac582363cac.png)
![image](https://user-images.githubusercontent.com/47509184/179479272-31506997-8967-4a21-924e-5689f2735be9.png)
また、今回フォロー中のアカウントのアカウント詳細ページに移動するとフォロワーが1になっていて確認してみると、先ほどのアカウントが一覧に含まれています。
![image](https://user-images.githubusercontent.com/47509184/179479721-a5bb25b1-88c8-41fe-aca9-4c0f8bb93bfb.png)
![image](https://user-images.githubusercontent.com/47509184/179479735-826fb28a-bb62-47fd-bc15-7564e1469dd6.png)

2022-07-18 22:43 UTC, TAK848 approved these changes
LGTM!!

2022-07-18 22:43 UTC, TAK848 commented on account/views.py
> +                "profile": account.profile,
（参考）これくらいであれば，テンプレート上で`account.profile`と参照しても良いかもしれませんね。

2022-07-18 22:43 UTC, TAK848 commented on account/models.py
> +    date_created = models.DateTimeField(auto_now_add=True)
（参考）
前回漏れていましたが，`created_at`を使用することが多いです
更新日時をもし使う場合は`updated_at`

2022-07-18 22:43 UTC, tak848 commented on account/urls.py
> +        "accounts/<int:account_id>/followee/",
（参考）urlに関しては，`followings`の方がわかりやすいかもしれません（モデル設計側と，ユーザー側の見方の違いによるものです）

2022-07-18 22:43 UTC, TAK848 commented on account/urls.py
> +        "accounts/<int:account_id>/follower/",
（参考）リストは複数形にした方がより良いですね（`followers`）

2022-07-19 12:28 UTC, Akinori13 requested changes
少しだけコメントしました！

2022-07-19 12:28 UTC, Akinori13 commented on twitter_clone/settings.py
> +# APPEND_SLASH = False
```suggestion
```

2022-07-19 12:28 UTC, Akinori13 commented on account/models.py
> +class FollowConnection(models.Model):
[複合ユニーク](https://djangobrothers.com/blogs/django_uniqueconstraint/)をつけてあげましょう

2022-07-19 12:28 UTC, Akinori13 commented on account/tests.py
> +        self.assertEqual(response.context["followee_num"], 0)
[メモ]DjangoはDBをテストの際に毎回データを抹消するので、あまり意味はないかもしれないです。（とはいえSetUpを通して予期できないことの発生も否定できないので、このような形で組み込むのも問題はないです。）

2022-07-20 10:02 UTC, Akinori13 commented
LGTM

2022-07-20 10:03 UTC, merged