いいね・いいね解除機能の実装
okapiinosuke/Backend_twitter_clone pull request #7
Opened 2022-08-11 08:26 UTC by okapiinosuke

いいね・いいね解除機能を実装しました。

- どのツイートに対してもいいね・いいね解除をできるようにしました。
- いいねの一覧を確認できるようにするために、アカウント詳細ページにいいねしたツイート一覧を確認できるタブを追加しました。

以下に実際に作成したページのスクリーンショットを示します。

- 各ツイートの左下にいいねボタンが追加されました。
![image](https://user-images.githubusercontent.com/47509184/184093489-8a41b2b6-0fa4-4045-a872-2b9e754a6c66.png)

- どのツイートにもいいねを押すことができます。
![image](https://user-images.githubusercontent.com/47509184/184093509-26a16e55-2475-4c29-8762-50c452c26308.png)

-  いいねを解除することもできます。
![image](https://user-images.githubusercontent.com/47509184/184093529-1c582c2e-938a-4194-8475-153305e3e0d9.png)

また、今回作成したテストを含め、全て通したことを以下に示します。
![image](https://user-images.githubusercontent.com/47509184/184093469-916ac269-b6b6-4012-8166-c4d568c65010.png)

2022-08-12 05:15 UTC, kunikida007 approved these changes

2022-08-12 05:47 UTC, Akinori13 requested changes
いい感じです！
フロントエンドとバックエンドで改善点があります！パフォーマンスにも注意を払い、読みやすいコードに修正してください！

2022-08-12 05:47 UTC, Akinori13 commented on tweet/models.py
> +    favorited = models.ForeignKey(
命名`tweet`など分かりやすくしてください

2022-08-12 05:47 UTC, Akinori13 commented on tweet/models.py
> +    favorite = models.ForeignKey(
命名`user`など分かりやすくしてください

2022-08-12 05:47 UTC, Akinori13 commented on account/views.py
> +            },
このViewは全体的に再度書き直してみてください。

以下でクエリのパフォーマンスを確認できます
```python
from django.db import reset_queries
from django.db import connection
reset_queries()
for query in connection.queries:
    print(query)
```

2022-08-12 05:47 UTC, Akinori13 commented on account/templates/account/home.html
> +
いいねした後にいいねの解除ができないです。
data属性等を持ちいてstatus（いいねかいいねしていないか）を保持してそれによってURL先を変更してあげるのがよいでしょう

2022-08-12 13:11 UTC, Akinori13 requested changes
いくつかコメントしました！

2022-08-12 13:11 UTC, Akinori13 commented on account/views.py
>          return redirect("/home/")
ハードコーディングしない。

2022-08-12 13:11 UTC, Akinori13 commented on account/views.py
>              form = TweetForm()
これいらない

2022-08-12 13:11 UTC, Akinori13 commented on account/views.py
> +
別にパフォーマンス自体にさほどの変化は生まれないと思いますが、以下でよいのではないでしょうか
```python
tweet_list = Tweet.objects.all()
favorited_tweet_id_list = request.user.favorite_account.values_list('favorited_tweet_id', flat=True)
```

2022-08-12 13:11 UTC, Akinori13 commented on tweet/views.py
> +    # return redirect("/home/")
使ってないものは消しちゃいましょう

2022-08-12 13:11 UTC, Akinori13 commented on tweet/views.py
> +        return JsonResponse(data)
ここ分けなくて大丈夫です

2022-08-12 13:11 UTC, Akinori13 commented on tweet/views.py
> +        return JsonResponse(data)
ここも同様

2022-08-12 13:11 UTC, Akinori13 commented on tweet/views.py
> +    # return redirect("/home/")
ここも

2022-08-12 13:11 UTC, Akinori13 commented on account/templates/account/home.html
> +  $(document).on("click", "#favorite", function() {
ここ下のunfavoriteと一つの関数にまとめてほしいです

2022-08-12 13:11 UTC, Akinori13 commented on tweet/tests.py
> +class FavoriteTest(TestCase):
最終課題テスト項目要件整理の所定のテストを満たしていないと思われますので、再確認をお願いします

2022-08-13 08:40 UTC, Akinori13 requested changes
すこし深い部分までコメントしています！！
実際に動作させて挙動を確認してみてください。あと少しです

2022-08-13 08:40 UTC, Akinori13 commented on account/views.py
> +        print(favorited_tweet_id_list)
消してください

2022-08-13 08:40 UTC, Akinori13 commented on account/views.py
>          return redirect("/home/")
ここ再度確認してください。

2022-08-13 08:40 UTC, Akinori13 commented on account/views.py
> +        return redirect(reverse("account:home"))
good

2022-08-13 08:40 UTC, Akinori13 commented on tweet/views.py
> +            return JsonResponse({"tweet_id": -1})
400返してあげましょう

2022-08-13 08:40 UTC, Akinori13 commented on tweet/views.py
> +            return JsonResponse({"tweet_id": -1})
404を返します

2022-08-13 08:40 UTC, Akinori13 commented on account/views.py
>                  "follow_flg": follow_flg,
見落としです。booleanの場合は`is_~`という命名にするのがよいです

2022-08-13 08:40 UTC, Akinori13 commented on tweet/views.py
> +            return JsonResponse({"tweet_id": -1})
400か404を返しましょう

2022-08-13 08:40 UTC, Akinori13 commented on tweet/views.py
> +            return JsonResponse({"tweet_id": -1})
ここも

2022-08-13 08:40 UTC, Akinori13 commented on tweet/views.py
> +        return JsonResponse({"tweet_id": tweet_id})
status_codeと一緒に返してあげましょう

2022-08-13 08:40 UTC, Akinori13 commented on tweet/views.py
> +        return JsonResponse({"tweet_id": tweet_id})
ここも

2022-08-13 08:40 UTC, Akinori13 commented on tweet/views.py
> +        return JsonResponse({"tweet_id": tweet_id})
201ですかね（[参考](https://qiita.com/unsoluble_sugar/items/b080a16701946fcfce70)）

2022-08-13 08:40 UTC, Akinori13 commented on tweet/views.py
> +        return JsonResponse({"tweet_id": tweet_id})
204ですかね

2022-08-13 08:40 UTC, Akinori13 commented on account/templates/account/home.html
> +        selector_button = document.getElementsByName(data.tweet_id);
const

2022-08-13 08:40 UTC, Akinori13 commented on account/templates/account/home.html
> +  $(document).on("click", "#favorite_button", function() {
修正の必要はないですが、idは特定の要素のみに使います

2022-08-13 08:40 UTC, Akinori13 commented on account/templates/account/home.html
> +              {% endif %}
ここ正しいですか

2022-08-13 08:40 UTC, Akinori13 commented on account/templates/account/home.html
> +              {% endif %}
flgではなく、`is-liked`などを用いましょう

2022-08-13 08:40 UTC, Akinori13 commented on account/templates/account/home.html
> +    }
ulrは正しくセットされますか？

2022-08-13 08:40 UTC, Akinori13 commented on account/templates/account/home.html
> +      body: body,
これ必要ですか

2022-08-13 08:40 UTC, Akinori13 commented on account/templates/account/home.html
> +              {% endif %}
is-likedがtrueの時にいいね解除を表示します。
is-likedがtrueのボタンをクリックした場合、unfavriteにPOSTする

以上を再確認してください

2022-08-13 08:40 UTC, Akinori13 commented on account/templates/account/home.html
> +        selector_button = document.getElementsByName(data.tweet_id);
以下だとだめですか
```suggestion
        selector_button = $(this);
```

2022-08-13 09:19 UTC, okapiinosuke commented on account/views.py
> +        return redirect(reverse("account:home"))
一つ上のコメントとこのコメントについて、修正すべき部分が見当たらないのですが、具体的にどのあたりか教えていただけないでしょうか。

2022-08-13 09:20 UTC, okapiinosuke commented on account/templates/account/home.html
> +    }
urlは問題なくセットされています。

2022-08-13 12:04 UTC, okapiinosuke commented on account/templates/account/home.html
> +      body: body,
bodyは必要なかったです。
POSTはInternal Server Error(500)が起きたため書いています。

2022-08-13 12:11 UTC, okapiinosuke commented on account/templates/account/home.html
> +    }
constを置くとurl is not definedとなるため、constを外すとうまく行きます。

2022-08-14 12:11 UTC, Akinori13 commented on account/views.py
> +        return redirect(reverse("account:home"))
もしかしたら指摘の箇所に誤りがあったかもしれないです。申し訳ないです。

念のため付記します！
```
return redirect("/home/")
````
上よりも下の方が望ましいです。というのもurlを`/your_home/`とかに変更した際にすべて修正しなければならなくなるからです。
```
return redirect(reverse("account:home"))
```

2022-08-14 12:12 UTC, Akinori13 commented on account/templates/account/home.html
> +      body: body,
メソッドは必要ですね！！

2022-08-14 12:13 UTC, Akinori13 commented on account/templates/account/home.html
> +    }
スコープへの注意が必要ですね！[参考記事](https://codezine.jp/article/detail/15431)

2022-08-14 12:29 UTC, Akinori13 requested changes
いくつかコメントしました！

2022-08-14 12:29 UTC, Akinori13 commented on account/templates/account/home.html
> +    console.log(url);
これは不要だと思うので消しちゃってください

2022-08-14 12:29 UTC, Akinori13 commented on tweet/tests.py
> +        self.path = reverse("tweet:favorite_tweet", args=[self.favorited_tweet1.id])
たいして変わりませんが、以下でも可能だと思います
```suggestion
self.user1 = Account.objects.create_user(
            email="sample1@example.com", username="sample1", password="instance1"
        )
        Profile.objects.create(user=Account.objects.get(username="sample1"))
        self.user2 = Account.objects.create_user(
            email="sample2@example.com", username="sample2", password="instance2"
        )
        Profile.objects.create(user=Account.objects.get(username="sample2"))

        self.favorited_tweet1 = Tweet.objects.create(user=self.user2, content="aaa")
        self.favorited_tweet2 = Tweet.objects.create(user=self.user1, content="bbb")

        self.client.force_login(self.user1)
        
        self.path = reverse("tweet:favorite_tweet", args=[self.favorited_tweet1.id])
```

2022-08-14 12:29 UTC, Akinori13 commented on tweet/tests.py
> +        self.assertEqual(FavoriteConnection.objects.all().count(), 1)
すでにいいねできることは確認できてますから、ここで敢えてテストする必要もないでしょう

2022-08-14 12:29 UTC, Akinori13 commented on tweet/tests.py
> +        )
すでにいいねできることは確認済みなので、データ登録（create）で済ましてもいいでしょう

2022-08-14 12:29 UTC, Akinori13 commented on tweet/tests.py
> +    def test_other_requests(self):
完全な余談ですが、subTestでdelte.put,patchのテストをしてもいいですね

2022-08-14 12:31 UTC, Akinori13 commented on tweet/views.py
> +@require_http_methods(["GET", "POST"])
追加ですが、GETはなぜ追記されていますか

2022-08-14 13:53 UTC, okapiinosuke commented on tweet/views.py
> +@require_http_methods(["GET", "POST"])
このコメントで勘違いしたかもしれないのですが、全てのビューにGETメソッドが必要だと考えてました。
https://github.com/okapiinosuke/Backend_twitter_clone/pull/5#discussion_r922650971
今回については、POSTメソッドのみで問題ないでしょうか。

2022-08-15 02:24 UTC, Akinori13 commented on tweet/views.py
> +@require_http_methods(["GET", "POST"])
全てのビューにGETメソッドは必要ないです。HTTPメソッドは[参考記事](https://developer.mozilla.org/ja/docs/Web/HTTP/Methods)のように使い分けがなされます。

しかし最終課題ではDjangoの仕様等を考慮して、GETとPOSTのみを用いて実装します。今回はデータの変更のみですからPOSTのみでよいです。

2022-08-15 02:26 UTC, Akinori13 commented on tweet/views.py
> +@require_http_methods(["GET", "POST"])
引用してくださったコメントの趣旨はGETでもPOSTでもデータの変更（と登録）というViewは実装できる。ゆえにどちらでも構わない。ただしデータの変更はどちらかと言えばPOSTに近いので、POSTの方が望ましいという意味だと思います！

2022-08-16 14:12 UTC, Akinori13 commented
LGTM

2022-08-16 14:12 UTC, Akinori13 approved these changes

2022-08-16 14:12 UTC, merged